<?php
  $lang['number']		= 'Reference';
  $lang['date'] 		= 'Billing date';
  $lang['time']			= 'Billing time';
  $lang['due'] 			= 'Due date';
  $lang['to'] 			= 'Order Detail';
  $lang['from'] 		= 'Billing & Delivery Address';
  $lang['product'] 		= 'Order item';
  $lang['qty'] 			= 'Qty';
  $lang['price'] 		= 'Price';
 // $lang['discount'] 	= 'Total';
  //$lang['vat'] 			= 'Vat';
  $lang['total'] 		= 'Total';
  $lang['page'] 		= 'Page';
  $lang['page_of'] 		= 'of';
?>
